version: '3.8'
services:
    db:
      image: postgres:13.0-alpine
      volumes:
        - db_value:/var/lib/postgresql/data/
      env_file:
        - ./.env

    backend:
      image: saborrr/foodgram_backend:v1.0
      restart: always
      volumes:
        - static_value:/app/static/
        - media_value:/app/media/
      depends_on:
        - db
      env_file:
        - ./.env

    frontend:
      image: saborrr/frontend:v1.0
      volumes:
        - ../frontend/:/app/result_build/
      depends_on:
      - backend

    nginx:
      image: nginx:1.18
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/default.conf
        - ../frontend/build:/usr/share/nginx/html/
        - ../docs/:/usr/share/nginx/html/api/docs/
        - static_value:/var/html/static/
        - media_value:/var/html/media/
      depends_on:
        - backend

volumes:
  db_value:
  static_value:
  media_value:
