# Generated by Django 3.2.9 on 2023-06-10 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230610_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Ой, ингредиентов не может быть меньше 1')], verbose_name='количество'),
        ),
    ]
